### ISSUE TITLE
Can't connect to ADP URL

### ISSUE THREAD

**Issue by tomdee** [rayhe/adp#2]
Traceback (most recent call last):
  File "./adp.py", line 162, in <module>
    main(sys.argv[1:])
  File "./adp.py", line 157, in main
    fetcher = PayCheckFetcher(username, password)
  File "./adp.py", line 31, in __init__
    self.getResponse(url='https://ipay.adp.com/iPay/private/index.jsf')
  File "./adp.py", line 47, in getResponse
    response = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol>

**Comment by jjmaestro** [comment]
FYI, "It works on my machine"<sup>(TM)</sup> :)

I think your network was failing. I'd close the issue, the script works perfectly.
